### PR TITLE
Start a modified document describing the Dataset graph pattern

### PR DESCRIPTION
**Pull request by mbjones**
In the `feature_14_graph_pattern` branch and this PR, the `mappings.md` file will be edited to describe our desired graph pattern for representing our core conceptual entities:

- Dataset
- Person
- Organization
- Identifier

and any others that we think are needed.

Currently this is an adaptation of the GeoLink graph pattern, and editing has only just begun to propose changes.

### CODE REVIEW

**Review by ThomasThelen — APPROVED** [review]

**Comment by mbjones** [comment]
Thanks Tommy. This PR is not ready for merge- I was just starting a branch and using the PR as an easy way for folks to see what changed. We need to finish editing the doc and make our decisions before we merge the PR.

**Comment by amoeba** [comment]
I finished up a first draft in https://github.com/DataONEorg/slinky/pull/21/commits/8e6cda2178c64230f065d0130ca2360cb6e080b6. I'm going to review on Monday and probably ask for notes after that.

**Comment by mbjones** [comment]
I did a quick read through, @amoeba -- looking good. While there were a lot of particulars that we can pick up on later, a couple high-level points. For provenance, I think we should follow the DataONE provenance model as expressed in the [SOSO provenance guidance](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#provenance-relationships). This will be quite compatible with Carl's approach, which is already pretty isomorphic with ProvONE albeit lacking some specific things. Second, when we have multiple values for a field, like for `identifier` with have PID, SID, and alternative Identifier fields, we can and should include them both, and follow SOSO guidance on indicating precedence and using `sameAs` in reasonable ways. For your example, it would be good to use an example that is pretty comprehensive and has both annotations and detailed provenance information to show how those would work. Finally, we should discuss the Dataset/Metadata/Entity/Package distinctions and how we will map those -- I was a little confused by your initial text around those. Nice work all around!

**Comment by amoeba** [comment]
Hi @mbjones, though we still have some changes up in the air (See https://github.com/DataONEorg/slinky/issues/64), I'd like to go ahead and merge this and continue working on addressing the feedback listed in https://github.com/DataONEorg/slinky/issues/64. The examples we went over in our hpad are already on develop under https://github.com/DataONEorg/slinky/tree/develop/d1lod/docs/examples and I think we can keep those in sync as I work to finish up the remaining issues in https://github.com/DataONEorg/slinky/issues/64.

Sound okay?

**Comment by mbjones** [comment]
Sounds good to me.

**Comment by amoeba** [comment]
Merged. Feedback related this PR can now be found in https://github.com/DataONEorg/slinky/issues/64.

**Pull request merged**
