### PR TITLE
Port the essential services from Docker to Kubernetes

### LINKED ISSUE #3: Migrate to Kubernetes
DataONE has a Kubernetes cluster that this stack should work nicely in. Migrate the docker swarm over to a Kubernetes Helm Chart and deploy it on the development cluster.

Once complete, do a fully integrated test to make sure that harvesting and graph population works the same (nothing should change from this). With Kubernetes, we should think about a new logging framework that integrates nicely with the whole stack. For now exclude them from the stack

Essential services to migrate:

- [x] Virtuoso
- [x] Redis
- [x] Scheduler
- [x] Worker

### LINKED ISSUE #10: Remove web & www directories
With the transition over to Virtuoso, we no longer need Apache + Tomcat to expose sesame and the work bench (since they're no longer used). The Apache+Tomcat container is in the `web/` folder, while the web stuff is in `www/`.

### PR DESCRIPTION
**Pull request by ThomasThelen**
This PR is mainly concerned with porting the essentials over to Kubernetes.

Fixes #3 
Fixes #10 

### Changes:
1. The first change is that I removed all of the docker related files.
2. Updated the README to reflect the Kubernetes deployment
3. Added a new directory, `deploy/` that contains the K8 Helm Chart
4. Refactored the Docker Image builds so that the commands are now in the K8 config files
5. Removed the `data/` folder since K8 works with PersistentVolume objects

### Kubernetes Details:
The most controversial thing that I can think of is that copying files from the host into a pod isn't a Kubernetes pattern. This amounts to some refactoring done around the Docker [COPY](https://github.com/DataONEorg/slinky/blob/main/scheduler/Dockerfile#L11) directive. The best way to do this is to bundle the requirements into a docker image, hosted on dockerhub, and pulled by K8. This allows for a streamlined deployment process that's agnostic of the hosts' filesystem. For the moment, I'm using my personal dockerhub to hold the scheduler & worker images. These should be moved over to the DataONE dockerhub at some point.

K8 still has a 'master' role for services, it looks like the issue is currently [unresolved](https://github.com/kubernetes/website/issues/6525) (it's apparently easier to close an issue that sparks debate than actually deal with it). I'll keep my eyes open for ways to come up with a better name.

### To Test:

1. Install & start minikube
2. Clone this repository and navigate to `deploy/`
3. Run `helm install ./ --generate-name`
4. Check that the pods and services are up
5. Run `minikube service virtuoso`
6. See that the virtuoso UI opens
7. Run a sparql query to check that data from DataONE has been inserted

#### Bonus Testing
Play around with setting replicas to 0 for various pods and check the logs of other pods to make sure they fail. Then bring the replica count back up and see that the other pods successfully find the pod. For example setting the replica count for the worker pod to 0 will cause the scheduler to fail. After setting it back to something greater than or equal to 1, the worker should be able to find it and continue processing data.

### Reviewing
The commits are fairly isolated and can be reviewed individually. 456bb45 concerns Kubernetes management and 683d625 concerns adding the Dockerfiles so that the Kubernetes stack can be updated with code changes.

### CODE REVIEW

**Comment by mbjones** [comment]
@ThomasThelen I retargeted this PR at `develop` so that it merges into the right branch. We shouldn't be merging from feature branches directly into main if we follow our release guidelines.

**Comment by mbjones** [comment]
Also, I am not going to have time to dive into this deeply in the next few days, so please have @amoeba review it and hopefully you two can merge to develop and keep moving forward.

**Comment by ThomasThelen** [comment]
Oops I always forget to retarget the branch there. Thanks!

**Comment by amoeba** [comment]
Thanks @ThomasThelen, I'll have a go here in a bit.

**Comment by amoeba** [comment]
Looks good to me @ThomasThelen. Nice work. I was able to get it running without any issues and confirm that triples were being inserted. I might have comments once merged or once we start developing/deploying but I think this is good to go as is.

**Pull request merged**
